
const demonString = `[
  {
    "Name": "Demi-Fiend",
    "Tier": 5,
    "MustBe": "King",
    "AttackType": "Almighty",
    "Resistance": "-",
    "Weakness": "-",
    "Skill": "-",
    "SkillType": "-",
    "Description": "*Can only be King"
  },
  {
    "Name": "Hero (SMT 1)",
    "Tier": 5,
    "MustBe": "King",
    "AttackType": "Almighty",
    "Resistance": "-",
    "Weakness": "-",
    "Skill": "-",
    "SkillType": "-",
    "Description": "*Can only be King"
  },
  {
    "Name": "Demonica (SJ)",
    "Tier": 5,
    "MustBe": "King",
    "AttackType": "Almighty",
    "Resistance": "-",
    "Weakness": "-",
    "Skill": "-",
    "SkillType": "-",
    "Description": "*Can only be King"
  },
  {
    "Name": "Flynn",
    "Tier": 5,
    "MustBe": "King",
    "AttackType": "Almighty",
    "Resistance": "-",
    "Weakness": "-",
    "Skill": "-",
    "SkillType": "-",
    "Description": "*Can only be King"
  },
  {
    "Name": "Nahobino",
    "Tier": 5,
    "MustBe": "King",
    "AttackType": "Almighty",
    "Resistance": "-",
    "Weakness": "-",
    "Skill": "-",
    "SkillType": "-",
    "Description": "*Can only be King"
  },
  {
    "Name": "Siegfried",
    "Tier": 4,
    "MustBe": "-",
    "AttackType": "Phys",
    "Resistance": "Phys",
    "Weakness": "Dark",
    "Skill": "Brave Blade",
    "SkillType": "Pierce",
    "Description": "Pierce"
  },
  {
    "Name": "Beelzebub",
    "Tier": 4,
    "MustBe": "-",
    "AttackType": "Dark",
    "Resistance": "Fire",
    "Weakness": "Light",
    "Skill": "Demonic Decree",
    "SkillType": "Pierce",
    "Description": "Pierce"
  },
  {
    "Name": "Metatron",
    "Tier": 4,
    "MustBe": "-",
    "AttackType": "Light",
    "Resistance": "Light",
    "Weakness": "Dark",
    "Skill": "Divine Judgement",
    "SkillType": "Pierce",
    "Description": "Pierce"
  },
  {
    "Name": "Pascal",
    "Tier": 4,
    "MustBe": "-",
    "AttackType": "Almighty",
    "Resistance": "-",
    "Weakness": "-",
    "Skill": "-",
    "SkillType": "-",
    "Description": ">Pascal the dog is here."
  },
  {
    "Name": "Lucifer",
    "Tier": 4,
    "MustBe": "-",
    "AttackType": "Almighty",
    "Resistance": "-",
    "Weakness": "-",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Loki",
    "Tier": 4,
    "MustBe": "-",
    "AttackType": "Ice",
    "Resistance": "Ice",
    "Weakness": "Fire",
    "Skill": "Niflheim",
    "SkillType": "Pierce",
    "Description": "Pierce"
  },
  {
    "Name": "Baal",
    "Tier": 4,
    "MustBe": "-",
    "AttackType": "Wind",
    "Resistance": "Wind",
    "Weakness": "Elec",
    "Skill": "Panta Rhei",
    "SkillType": "Pierce",
    "Description": "Pierce"
  },
  {
    "Name": "Surt",
    "Tier": 4,
    "MustBe": "-",
    "AttackType": "Fire",
    "Resistance": "Fire",
    "Weakness": "Ice",
    "Skill": "Ragnarok",
    "SkillType": "Pierce",
    "Description": "Pierce"
  },
  {
    "Name": "Cybele",
    "Tier": 4,
    "MustBe": "-",
    "AttackType": "Light",
    "Resistance": "Wind",
    "Weakness": "Phys",
    "Skill": "Samarecarm",
    "SkillType": "-",
    "Description": "Revive pawn on bottom most possible space (starting from left side)."
  },
  {
    "Name": "Ishtar",
    "Tier": 4,
    "MustBe": "-",
    "AttackType": "Elec",
    "Resistance": "Elec",
    "Weakness": "Phys",
    "Skill": "Samarecarm",
    "SkillType": "-",
    "Description": "Revive pawn on bottom most possible space (starting from left side)."
  },
  {
    "Name": "Odin",
    "Tier": 4,
    "MustBe": "-",
    "AttackType": "Elec",
    "Resistance": "Elec",
    "Weakness": "Wind",
    "Skill": "Thunder Reign",
    "SkillType": "Pierce",
    "Description": "Pierce"
  },
  {
    "Name": "Scathach",
    "Tier": 3,
    "MustBe": "-",
    "AttackType": "Ice",
    "Resistance": "Wind",
    "Weakness": "Fire",
    "Skill": "Bufudyne",
    "SkillType": "-",
    "Description": "Can claim a piece from 1 space away. Target must be weak to Ice."
  },
  {
    "Name": "Trumpeter",
    "Tier": 3,
    "MustBe": "-",
    "AttackType": "Support",
    "Resistance": "-",
    "Weakness": "-",
    "Skill": "Evil Melody",
    "SkillType": "-",
    "Description": "If a piece takes him, they also die. He can still check the King."
  },
  {
    "Name": "Cu Chulainn",
    "Tier": 3,
    "MustBe": "-",
    "AttackType": "Wind",
    "Resistance": "Wind",
    "Weakness": "Elec",
    "Skill": "Gae Bolg",
    "SkillType": "-",
    "Description": "Can run over up to 2 adjacent enemy pieces in a straight line as long as neither resists."
  },
  {
    "Name": "White Rider",
    "Tier": 3,
    "MustBe": "-",
    "AttackType": "Light",
    "Resistance": "Ice",
    "Weakness": "Fire",
    "Skill": "God's Bow",
    "SkillType": "Pierce",
    "Description": "Pierce"
  },
  {
    "Name": "Principality",
    "Tier": 3,
    "MustBe": "-",
    "AttackType": "Light",
    "Resistance": "Light",
    "Weakness": "Dark",
    "Skill": "Hamaon",
    "SkillType": "-",
    "Description": "Can claim a piece from 1 space away. Target must be weak to Light."
  },
  {
    "Name": "Hell Biker",
    "Tier": 3,
    "MustBe": "-",
    "AttackType": "Fire",
    "Resistance": "Dark",
    "Weakness": "Ice",
    "Skill": "Hell Burner",
    "SkillType": "-",
    "Description": "Can run over up to 2 adjacent enemy pieces in a straight line as long as neither resists."
  },
  {
    "Name": "Girimekhala",
    "Tier": 3,
    "MustBe": "-",
    "AttackType": "Phys",
    "Resistance": "Phys",
    "Weakness": "Light",
    "Skill": "One-Shot Kill",
    "SkillType": "-",
    "Description": "Upon capture, roll a D6. If 6 is rolled, he can move/capture again. Can be repeated until D6 fails."
  },
  {
    "Name": "Daisoujou",
    "Tier": 3,
    "MustBe": "-",
    "AttackType": "Light",
    "Resistance": "Light",
    "Weakness": "Phys",
    "Skill": "Samsara",
    "SkillType": "-",
    "Description": "Choose 2 spaces within the box to attack. Targets who resist aren't affected."
  },
  {
    "Name": "Black Rider",
    "Tier": 3,
    "MustBe": "-",
    "AttackType": "Dark",
    "Resistance": "Dark",
    "Weakness": "Light",
    "Skill": "Soul Divide",
    "SkillType": "-",
    "Description": "Choose 2 spaces within the box to attack. Targets who resist aren't affected."
  },
  {
    "Name": "Seth",
    "Tier": 3,
    "MustBe": "-",
    "AttackType": "Wind",
    "Resistance": "Fire",
    "Weakness": "Light",
    "Skill": "Zandyne",
    "SkillType": "-",
    "Description": "Can claim a piece from 1 space away. Target must be weak to Wind."
  },
  {
    "Name": "Thor",
    "Tier": 3,
    "MustBe": "-",
    "AttackType": "Elec",
    "Resistance": "Phys",
    "Weakness": "Wind",
    "Skill": "Ziodyne",
    "SkillType": "-",
    "Description": "Can claim a piece from 1 space away. Target must be weak to Elec."
  },
  {
    "Name": "Sati",
    "Tier": 2,
    "MustBe": "-",
    "AttackType": "Fire",
    "Resistance": "Fire",
    "Weakness": "Ice",
    "Skill": "Agidyne",
    "SkillType": "-",
    "Description": "Can claim a piece from 1 space away. Target must be weak to Fire."
  },
  {
    "Name": "Throne",
    "Tier": 2,
    "MustBe": "-",
    "AttackType": "Light",
    "Resistance": "Fire",
    "Weakness": "Dark",
    "Skill": "Auto-Rakukaja",
    "SkillType": "-",
    "Description": "Can only be taken by Almighty/Weakness for the first 3 turns"
  },
  {
    "Name": "Nekomata",
    "Tier": 2,
    "MustBe": "-",
    "AttackType": "Phys",
    "Resistance": "Wind",
    "Weakness": "Elec",
    "Skill": "Auto-Sukukaja",
    "SkillType": "-",
    "Description": "For the first 3 turns, this piece may make 2 movements. An attack may only be made on the first move."
  },
  {
    "Name": "Rakshasa",
    "Tier": 2,
    "MustBe": "-",
    "AttackType": "Phys",
    "Resistance": "Phys",
    "Weakness": "Wind",
    "Skill": "Auto-Tarukaja",
    "SkillType": "-",
    "Description": "If he takes a piece within the first 3 turns, gets a free 1-more (doesn't need to hit weakness)"
  },
  {
    "Name": "Mother Harlot",
    "Tier": 2,
    "MustBe": "Knight",
    "AttackType": "Ice",
    "Resistance": "Elec",
    "Weakness": "Phys",
    "Skill": "Death Lust",
    "SkillType": "-",
    "Description": "FE 2 space range - can use turn to move enemy pawn forward or backward one square."
  },
  {
    "Name": "Mothman",
    "Tier": 2,
    "MustBe": "-",
    "AttackType": "Elec",
    "Resistance": "Elec",
    "Weakness": "Ice",
    "Skill": "Eerie Sound",
    "SkillType": "-",
    "Description": "Pawns cannot defeat Mothman for 1 turn"
  },
  {
    "Name": "Incubus",
    "Tier": 2,
    "MustBe": "Knight",
    "AttackType": "Almighty",
    "Resistance": "Dark",
    "Weakness": "Phys",
    "Skill": "Energy Drain",
    "SkillType": "OneMore",
    "Description": "Gets a 1-more if taking a bishop"
  },
  {
    "Name": "Yaksini",
    "Tier": 2,
    "MustBe": "-",
    "AttackType": "Phys",
    "Resistance": "Phys",
    "Weakness": "Fire",
    "Skill": "Getsu-ei",
    "SkillType": "-",
    "Description": "Can claim a piece from 1 space away. Target must be weak to Phys."
  },
  {
    "Name": "Forneus",
    "Tier": 2,
    "MustBe": "-",
    "AttackType": "Ice",
    "Resistance": "Ice",
    "Weakness": "Fire",
    "Skill": "Makarakarn",
    "SkillType": "-",
    "Description": "Null capture for one turn. Ends turn. You can't move at beginning of turn thats it foo"
  },
  {
    "Name": "Black Frost",
    "Tier": 2,
    "MustBe": "-",
    "AttackType": "Dark",
    "Resistance": "Dark",
    "Weakness": "Light",
    "Skill": "Mudoon",
    "SkillType": "-",
    "Description": "Can claim a piece from 1 space away. Target must be weak to Dark."
  },
  {
    "Name": "Matador",
    "Tier": 2,
    "MustBe": "Bishop",
    "AttackType": "Wind",
    "Resistance": "Wind",
    "Weakness": "Elec",
    "Skill": "Red Capote",
    "SkillType": "-",
    "Description": "Can move one space left or right. This uses a turn."
  },
  {
    "Name": "Succubus",
    "Tier": 2,
    "MustBe": "Bishop",
    "AttackType": "Almighty",
    "Resistance": "Dark",
    "Weakness": "Phys",
    "Skill": "Soul Drain",
    "SkillType": "OneMore",
    "Description": "Gets a 1-more if taking a knight"
  },
  {
    "Name": "Eligor",
    "Tier": 2,
    "MustBe": "-",
    "AttackType": "Phys",
    "Resistance": "Phys",
    "Weakness": "Elec",
    "Skill": "Sukukaja",
    "SkillType": "-",
    "Description": "If adjacent to ally pawn at the beginning of the turn, you may move that pawn forward 2 squares."
  },
  {
    "Name": "Red Rider",
    "Tier": 2,
    "MustBe": "-",
    "AttackType": "Phys",
    "Resistance": "Dark",
    "Weakness": "Ice",
    "Skill": "Terror Blade",
    "SkillType": "Pierce",
    "Description": "Pierce"
  },
  {
    "Name": "Decarabia",
    "Tier": 2,
    "MustBe": "-",
    "AttackType": "Ice",
    "Resistance": "Light",
    "Weakness": "Phys",
    "Skill": "Tetrakarn",
    "SkillType": "-",
    "Description": "Null capture for one turn. Ends turn. You can't move at beginning of turn thats it foo"
  },
  {
    "Name": "Pale Rider",
    "Tier": 2,
    "MustBe": "-",
    "AttackType": "Support",
    "Resistance": "Phys",
    "Weakness": "Light",
    "Skill": "Toxic Cloud",
    "SkillType": "-",
    "Description": "If checks King, can poison adjacent piece. That piece is taken after opponent's next turn."
  },
  {
    "Name": "Ame-no-Uzume",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Light",
    "Resistance": "Elec",
    "Weakness": "Phys",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Angel",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Light",
    "Resistance": "Light",
    "Weakness": "Phys",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Ara Mitama",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Fire",
    "Resistance": "Fire",
    "Weakness": "Ice",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Berith",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Phys",
    "Resistance": "Light",
    "Weakness": "Ice",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Black Ooze",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Almighty",
    "Resistance": "-",
    "Weakness": "All",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Fortuna",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Wind",
    "Resistance": "Wind",
    "Weakness": "Elec",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Hua Po",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Fire",
    "Resistance": "Dark",
    "Weakness": "Phys",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Jack Frost",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Ice",
    "Resistance": "Ice",
    "Weakness": "Fire",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Kusi Mitama",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Wind",
    "Resistance": "Wind",
    "Weakness": "Elec",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Lilim",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Dark",
    "Resistance": "Dark",
    "Weakness": "Light",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Mandrake",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Elec",
    "Resistance": "Wind",
    "Weakness": "Fire",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Mokoi",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Dark",
    "Resistance": "Dark",
    "Weakness": "Light",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Nigi Mitama",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Ice",
    "Resistance": "Ice",
    "Weakness": "Fire",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Pixie",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Wind",
    "Resistance": "Light",
    "Weakness": "Phys",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Preta",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Phys",
    "Resistance": "Dark",
    "Weakness": "Elec",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Pyro Jack",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Fire",
    "Resistance": "Fire",
    "Weakness": "Ice",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Saki Mitama",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Elec",
    "Resistance": "Elec",
    "Weakness": "Wind",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  },
  {
    "Name": "Slime",
    "Tier": 1,
    "MustBe": "Pawn",
    "AttackType": "Almighty",
    "Resistance": "-",
    "Weakness": "All",
    "Skill": "-",
    "SkillType": "-",
    "Description": "-"
  }
]`



export const demonData = JSON.parse(demonString)
